name: batch_job
description: Tools for running batch jobs
version: 0.7.0
author: Jim Philbin <jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/batch_job

environment:
  sdk: '>=1.24.2 <2.1.0'

dependencies:
  args: any
  core:
    path: C:/odw/sdk/core
    version: ^0.7.5
  convert:
    path: C:/odw/sdk/converter
    version: ^0.7.6
  io:
    path: C:/odw/sdk/io_extended
    version: ^0.7.5

dev_dependencies:
  benchmark_harness: ^1.0.4
  grinder: ^0.8.0+2
  test:  ^0.12.24
  test_tools:
    path: C:/odw/test_tools
    version: ^0.7.5
