name: batch_job
description: Tools for running batch jobs
version: 0.7.0
author: Jim Philbin <jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/batch_job

environment:
  sdk: ^2.0.0

dependencies:
  args: any
  core:
    path: C:/odw/sdk/core
    version: ^0.7.5
  converter:
    path: C:/odw/sdk/converter
    version: ^0.7.5
  io_extended:
    path: C:/odw/sdk/io_extended
    version: ^0.7.5

dev_dependencies:
  benchmark_harness: any
  grinder: ^0.8.0+2
  test:  any
  test_tools:
    path: C:/odw/test_tools
    version: ^0.7.5
